// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/superosystem/trainingsystem-backend/src/domain"
	mock "github.com/stretchr/testify/mock"
)

// AssignmentUsecase is an autogenerated mock type for the AssignmentUsecase type
type AssignmentUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: assignmentDomain
func (_m *AssignmentUsecase) Create(assignmentDomain *domain.Assignment) error {
	ret := _m.Called(assignmentDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Assignment) error); ok {
		r0 = rf(assignmentDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: assignmentId
func (_m *AssignmentUsecase) Delete(assignmentId string) error {
	ret := _m.Called(assignmentId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(assignmentId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByCourseId provides a mock function with given fields: courseId
func (_m *AssignmentUsecase) FindByCourseId(courseId string) (*domain.Assignment, error) {
	ret := _m.Called(courseId)

	var r0 *domain.Assignment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Assignment, error)); ok {
		return rf(courseId)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Assignment); ok {
		r0 = rf(courseId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Assignment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(courseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: assignmentId
func (_m *AssignmentUsecase) FindById(assignmentId string) (*domain.Assignment, error) {
	ret := _m.Called(assignmentId)

	var r0 *domain.Assignment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Assignment, error)); ok {
		return rf(assignmentId)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Assignment); ok {
		r0 = rf(assignmentId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Assignment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(assignmentId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: assignmentId, assignmentDomain
func (_m *AssignmentUsecase) Update(assignmentId string, assignmentDomain *domain.Assignment) error {
	ret := _m.Called(assignmentId, assignmentDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *domain.Assignment) error); ok {
		r0 = rf(assignmentId, assignmentDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAssignmentUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewAssignmentUsecase creates a new instance of AssignmentUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAssignmentUsecase(t mockConstructorTestingTNewAssignmentUsecase) *AssignmentUsecase {
	mock := &AssignmentUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
