// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/superosystem/trainingsystem-backend/src/domain"
	mock "github.com/stretchr/testify/mock"
)

// DetailCourseUsecase is an autogenerated mock type for the DetailCourseUsecase type
type DetailCourseUsecase struct {
	mock.Mock
}

// DetailCourse provides a mock function with given fields: courseId
func (_m *DetailCourseUsecase) DetailCourse(courseId string) (*domain.DetailCourse, error) {
	ret := _m.Called(courseId)

	var r0 *domain.DetailCourse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.DetailCourse, error)); ok {
		return rf(courseId)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.DetailCourse); ok {
		r0 = rf(courseId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DetailCourse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(courseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DetailCourseEnrolled provides a mock function with given fields: menteeId, courseId
func (_m *DetailCourseUsecase) DetailCourseEnrolled(menteeId string, courseId string) (*domain.DetailCourse, error) {
	ret := _m.Called(menteeId, courseId)

	var r0 *domain.DetailCourse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*domain.DetailCourse, error)); ok {
		return rf(menteeId, courseId)
	}
	if rf, ok := ret.Get(0).(func(string, string) *domain.DetailCourse); ok {
		r0 = rf(menteeId, courseId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DetailCourse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(menteeId, courseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDetailCourseUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewDetailCourseUsecase creates a new instance of DetailCourseUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDetailCourseUsecase(t mockConstructorTestingTNewDetailCourseUsecase) *DetailCourseUsecase {
	mock := &DetailCourseUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
