// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ManageMenteeUsecase is an autogenerated mock type for the ManageMenteeUsecase type
type ManageMenteeUsecase struct {
	mock.Mock
}

// DeleteAccess provides a mock function with given fields: menteeId, courseId
func (_m *ManageMenteeUsecase) DeleteAccess(menteeId string, courseId string) error {
	ret := _m.Called(menteeId, courseId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(menteeId, courseId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewManageMenteeUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewManageMenteeUsecase creates a new instance of ManageMenteeUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewManageMenteeUsecase(t mockConstructorTestingTNewManageMenteeUsecase) *ManageMenteeUsecase {
	mock := &ManageMenteeUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
