// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/superosystem/trainingsystem-backend/src/domain"
	mock "github.com/stretchr/testify/mock"
)

// MenteeProgressUsecase is an autogenerated mock type for the MenteeProgressUsecase type
type MenteeProgressUsecase struct {
	mock.Mock
}

// Add provides a mock function with given fields: menteeProgressDomain
func (_m *MenteeProgressUsecase) Add(menteeProgressDomain *domain.MenteeProgress) error {
	ret := _m.Called(menteeProgressDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.MenteeProgress) error); ok {
		r0 = rf(menteeProgressDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindMaterialEnrolled provides a mock function with given fields: menteeId, materialId
func (_m *MenteeProgressUsecase) FindMaterialEnrolled(menteeId string, materialId string) (*domain.MenteeProgress, error) {
	ret := _m.Called(menteeId, materialId)

	var r0 *domain.MenteeProgress
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*domain.MenteeProgress, error)); ok {
		return rf(menteeId, materialId)
	}
	if rf, ok := ret.Get(0).(func(string, string) *domain.MenteeProgress); ok {
		r0 = rf(menteeId, materialId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MenteeProgress)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(menteeId, materialId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMenteeProgressUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewMenteeProgressUsecase creates a new instance of MenteeProgressUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMenteeProgressUsecase(t mockConstructorTestingTNewMenteeProgressUsecase) *MenteeProgressUsecase {
	mock := &MenteeProgressUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
