// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/superosystem/trainingsystem-backend/src/domain"
	mock "github.com/stretchr/testify/mock"
)

// ReviewUsecase is an autogenerated mock type for the ReviewUsecase type
type ReviewUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: reviewDomain
func (_m *ReviewUsecase) Create(reviewDomain *domain.Review) error {
	ret := _m.Called(reviewDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Review) error); ok {
		r0 = rf(reviewDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByCourse provides a mock function with given fields: courseId
func (_m *ReviewUsecase) FindByCourse(courseId string) ([]domain.Review, error) {
	ret := _m.Called(courseId)

	var r0 []domain.Review
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.Review, error)); ok {
		return rf(courseId)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.Review); ok {
		r0 = rf(courseId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Review)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(courseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByMentee provides a mock function with given fields: menteeId, title
func (_m *ReviewUsecase) FindByMentee(menteeId string, title string) ([]domain.Review, error) {
	ret := _m.Called(menteeId, title)

	var r0 []domain.Review
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]domain.Review, error)); ok {
		return rf(menteeId, title)
	}
	if rf, ok := ret.Get(0).(func(string, string) []domain.Review); ok {
		r0 = rf(menteeId, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Review)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(menteeId, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewReviewUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewReviewUsecase creates a new instance of ReviewUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReviewUsecase(t mockConstructorTestingTNewReviewUsecase) *ReviewUsecase {
	mock := &ReviewUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
