// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/superosystem/trainingsystem-backend/src/domain"
	mock "github.com/stretchr/testify/mock"
)

// CategoryRepository is an autogenerated mock type for the CategoryRepository type
type CategoryRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: categoryDomain
func (_m *CategoryRepository) Create(categoryDomain *domain.Category) error {
	ret := _m.Called(categoryDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Category) error); ok {
		r0 = rf(categoryDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields:
func (_m *CategoryRepository) FindAll() (*[]domain.Category, error) {
	ret := _m.Called()

	var r0 *[]domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func() (*[]domain.Category, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *[]domain.Category); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *CategoryRepository) FindById(id string) (*domain.Category, error) {
	ret := _m.Called(id)

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Category, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Category); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, categoryDomain
func (_m *CategoryRepository) Update(id string, categoryDomain *domain.Category) error {
	ret := _m.Called(id, categoryDomain)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *domain.Category) error); ok {
		r0 = rf(id, categoryDomain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCategoryRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewCategoryRepository creates a new instance of CategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCategoryRepository(t mockConstructorTestingTNewCategoryRepository) *CategoryRepository {
	mock := &CategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
