version: '2.3'

services:
  orm-hibernate:
    container_name: "orm-hibernate"
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: hibernate
      POSTGRES_USER: hibernate
      POSTGRES_DB: hibernate_db
